@startuml
!$bg           = "#1e1e1e"
!$bg_l         = "#262626"
!$fg           = "#abb2bf"
!$red          = "#e06c75"
!$green        = "#98c379"
!$yellow       = "#e5c07b"
!$lighter_bg   = "#e8e8e8"
!$purple       = "#c678dd"
!$teal         = "#56b6c2"
skinparam backgroundColor $bg
skinparam {
  ActivityBackgroundColor        $bg_l
  ActivityBarColor               $fg
  ActivityBorderColor            $lighter_bg
  ActivityDiamondBackgroundColor $bg_l
  ActivityDiamondBorderColor     $lighter_bg
  ActivityEndColor               $red
  ActivityStartColor             $green
  ActorBackgroundColor        $bg_l
  ActorBorderColor            $lighter_bg
  ActorStereotypeFontColor    $fg
  AgentBackgroundColor       $bg_l
  AgentBorderColor           $fg
  ArrowColor $lighter_bg
  ArtifactBackgroundColor     $bg_l
  ArtifactBorderColor         $fg
  BackgroundColor $bg
  BoundaryBackgroundColor     $bg_l
  BoundaryBorderColor         $lighter_bg
  BoundaryStereotypeFontColor $fg
  CaptionFontColor $fg
  CardBackgroundColor     $bg_l
  CardBorderColor         $fg
  CircledCharacterFontColor $bg
  ClassBackgroundColor   $bg_l
  ClassBorderColor       $fg
  CloudBorderColor     $fg
  CollectionsBackgroundColor $bg_l
  CollectionsBorderColor     $lighter_bg
  ComponentBackgroundColor       $bg_l
  ComponentBorderColor           $lighter_bg
  ControlBackgroundColor $bg_l
  ControlBorderColor     $lighter_bg
  ControlFontColor       $fg
  ControlStereotypeFontColor $fg
  DatabaseBorderColor           $fg
  DefaultFontColor $fg
  DefaultFontName -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
  EntityBackgroundColor $bg_l
  EntityBorderColor     $lighter_bg
  FileBackgroundColor $bg_l
  FileBorderColor     $fg
  FolderBorderColor       $fg
  FrameBorderColor           $fg
  InterfaceBackgroundColor       $bg_l
  InterfaceBorderColor           $lighter_bg
  LegendBackgroundColor   $bg_l
  LegendBorderColor       $fg
  NodeBorderColor           $fg
  NoteBackgroundColor   $yellow
  NoteBorderColor       $bg
  NoteFontColor         $bg
  ObjectBackgroundColor       $bg_l
  ObjectBorderColor           $lighter_bg
  PackageBorderColor           $fg
  ParticipantBackgroundColor $bg_l
  ParticipantBorderColor     $lighter_bg
  PartitionBackgroundColor transparent
  PartitionBorderColor     $fg
  QueueBackgroundColor       $bg_l
  QueueBorderColor           $lighter_bg
  RectangleBorderColor           $fg
  SequenceBoxBackgroundColor $bg_l
  SequenceBoxBorderColor     $lighter_bg
  SequenceDividerBackgroundColor   $bg_l
  SequenceDividerBorderColor       $fg
  SequenceGroupBackgroundColor       $bg_l
  SequenceGroupBorderColor           $fg
  SequenceLifeLineBackgroundColor   transparent
  SequenceLifeLineBorderColor       $lighter_bg
  SequenceNewpageSeparatorColor  $fg
  SequenceReferenceBackgroundColor        transparent
  SequenceReferenceBorderColor            $fg
  SequenceReferenceHeaderBackgroundColor $bg_l
  Shadowing false
  StackBackgroundColor       $bg_l
  StackBorderColor           $lighter_bg
  StateBackgroundColor    $bg_l
  StateBorderColor        $lighter_bg
  StateEndColor           $red
  StateStartColor         $green
  StereotypeABackgroundColor   $lighter_bg
  StereotypeABorderColor       $lighter_bg
  StereotypeCBackgroundColor   $green
  StereotypeCBorderColor       $green
  StereotypeEBackgroundColor   $yellow
  StereotypeEBorderColor       $yellow
  StereotypeIBackgroundColor   $purple
  StereotypeIBorderColor       $purple
  StorageBackgroundColor $bg_l
  StorageBorderColor     $fg
  SwimlaneBorderColor            $fg
  UsecaseBackgroundColor       $bg_l
  UsecaseBorderColor           $lighter_bg
}
@enduml
